volumes:
  postgres_data:
  redis_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bot:
    build:
      dockerfile: Dockerfile.bot
    depends_on:
      - db
      - redis
    env_file: .env

  django:
    build:
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env

