# Generated by Django 3.2.16 on 2025-05-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='shoppingcartitems',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
