# Generated by Django 3.2.16 on 2025-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20250521_1318'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcartitems',
            name='item_shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'subcategory'), name='unique_name_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartitems',
            constraint=models.UniqueConstraint(fields=('shopping_cart', 'item'), name='unique_item_shopping_cart'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category'),
        ),
    ]
