# Generated by Django 3.2.16 on 2025-05-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20250521_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcartitems',
            name='unique_item_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitems',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='shoppingcartitems',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='shop.tguser'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shoppingcartitems',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_item_shopping_cart'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
