# Generated by Django 3.2.16 on 2025-05-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_questionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('question',), 'verbose_name': 'вопрос-ответ', 'verbose_name_plural': 'FAQ'},
        ),
    ]
